feat: add pagination
tenadopt/mini-paint pull request #24
Opened 2024-08-09 16:13 UTC by tenadopt

Add pagination for 15 images.

2024-08-12 08:41 UTC, shev7 requested changes
pagination should look like this 
<img width="451" alt="image" src="https://github.com/user-attachments/assets/707ca579-4456-45ff-84b3-0a8156a6eff7">
And current page must be used from search params, so you don't need local component state, just use search params

2024-08-12 08:41 UTC, shev7 commented on src/entities/image/VirtualizedImageList.tsx
> +                    </CardContent>
move image to separate component, if its related to work it shold be `WorkCard` or smth like this

2024-08-12 08:41 UTC, shev7 commented on src/entities/image/VirtualizedImageList.tsx
> +const ImageGrid = ({ images, onEdit, onDelete }: ImageGridProps) => (
shouldn't this be `WorkGrid`

2024-08-12 08:41 UTC, shev7 commented on src/pages/ImageFeed/ui/ImageFeedPage.tsx
> +import React, {useState} from 'react';
not formatted

2024-08-12 08:41 UTC, shev7 commented on src/entities/image/VirtualizedImageList.tsx
Shouldn't this be in`ui` segment of entity, and entity should be named like work i guess, its not an image, it is a work

2024-08-12 08:41 UTC, shev7 commented on src/entities/image/VirtualizedImageList.tsx
please follow fsd architecture

2024-08-12 14:56 UTC, tenadopt commented on src/entities/image/VirtualizedImageList.tsx
> +                    </CardContent>
I rename to Image Card. Nodody makes mistake.

2024-08-12 15:03 UTC, tenadopt commented on src/entities/image/VirtualizedImageList.tsx
I made the image as entity

2024-08-12 15:04 UTC, tenadopt commented on src/entities/image/VirtualizedImageList.tsx
> +const ImageGrid = ({ images, onEdit, onDelete }: ImageGridProps) => (
I make the image as entity.

2024-08-13 08:58 UTC, shev7 approved these changes

2024-08-13 12:12 UTC, merged