Filter
tenadopt/mini-paint pull request #3
Opened 2024-07-22 11:15 UTC by tenadopt

2024-07-23 06:51 UTC, shev7 requested changes

2024-07-23 06:51 UTC, shev7 commented on package.json
> +    "@types/react-router-dom": "^5.3.3",
should be dev dependecy

2024-07-23 06:51 UTC, shev7 commented on src/app/routes.tsx
> +const RequireAuth: React.FC<RequireAuthProps> = ({ children }) => {
no need to use to type components
```suggestion
const RequireAuth = ({ children }: RequireAuthProps) => {
```

2024-07-23 06:51 UTC, shev7 commented on src/app/routes.tsx
> +    );
```suggestion
if (auth.userId) {
   return <Navigate to="/feed" replace />
}

    return (
        <AppLayout>
            <Outlet />
        </AppLayout>
    );
```
please simplify conditions, avoid using ternary operators

2024-07-23 06:51 UTC, shev7 commented on src/app/routes.tsx
>                      <Suspense fallback={<Box display="flex" justifyContent="center" alignItems="center" height="100vh"><CircularProgress /></Box>}>
use suspense inside of layout

2024-07-23 06:51 UTC, shev7 commented on src/app/routes.tsx
>                      <Suspense fallback={<Box display="flex" justifyContent="center" alignItems="center" height="100vh"><CircularProgress /></Box>}>
in this kase you want need to wrap each page into it

2024-07-23 06:51 UTC, shev7 commented on src/features/imageGallery/api/imageService.ts
> +    })) as Image[];
```suggestion
    return querySnapshot.docs.map<Image>(doc => ({
        id: doc.id,
        ...doc.data(),
        createdAt: doc.data().createdAt.toDate()
    }));
```

2024-07-23 06:51 UTC, shev7 commented on src/features/works/api/worksServices.ts
> +    return querySnapshot.docs.map((doc) => ({
```suggestion
    const querySnapshot = await getDocs(q);
    
    return querySnapshot.docs.map((doc) => ({
```

2024-07-23 06:51 UTC, shev7 commented on src/features/works/api/worksServices.ts
> +    }
```suggestion
    if (docSnap.exists()) {
        return { id: docSnap.id, ...(docSnap.data() as Omit<Work, 'id'>), createdAt: docSnap.data().createdAt.toDate() };

        return null;
```

or more simplified

```suggestion
    if (!docSnap.exists()) {
        return null;
        };

       return { id: docSnap.id, ...(docSnap.data() as Omit<Work, 'id'>), createdAt: docSnap.data().createdAt.toDate() 
```

2024-07-23 06:51 UTC, shev7 commented on src/features/works/api/worksServices.ts
> +};
```suggestion
export const addWork = (work: Omit<Work, 'id' | 'createdAt'>): Promise<void> => {
   return addDoc(collection(db, 'works'), {
        ...work,
        createdAt: new Date()
    });
};
```
redundant async/await, await it where it's needed

2024-07-23 06:51 UTC, shev7 commented on src/features/works/api/worksServices.ts
> +};
same here with async/await, just return like in previous example

2024-07-23 06:51 UTC, shev7 commented on src/pages/Home/ui/HomePage.tsx
> +        loadWorks().catch(console.error);
add notifications, for example using react-toastify

2024-07-23 06:51 UTC, shev7 commented on src/pages/Home/ui/HomePage.tsx
> +                                        Delete
this is very hard to read due to ternaries, please avoid using them

2024-07-23 06:51 UTC, shev7 commented on src/pages/ImageEditor/ui/ImageEditorPage.tsx
> +        loadWork().catch(console.error);
really hard to read condition, avoid if blocks nesting, try to use early returns like we discussed

2024-07-23 06:51 UTC, shev7 commented on src/pages/ImageEditor/ui/ImageEditorPage.tsx
> +                            helperText={errors.description?.message}
also unreadable due to ternaries

2024-07-23 06:51 UTC, shev7 commented on src/pages/ImageEditor/ui/ImageEditorPage.tsx
> +                            {loading ? 'Saving...' : isEditing ? 'Update Work' : 'Create Work'}
spinner component can be used

2024-07-23 06:51 UTC, shev7 commented on src/pages/ImageFeed/ui/ImageFeedPage.tsx
> +                            </Card>
again ternaries

2024-07-23 06:51 UTC, shev7 commented on src/pages/Work/ui/WorkPage.tsx
> +            console.error('Error updating work:', error);
notification

2024-07-23 06:51 UTC, shev7 commented on src/pages/Work/ui/WorkPage.tsx
> +            ) : null}
ternaries

2024-07-23 06:51 UTC, shev7 commented on src/widgets/AppLayout.tsx
>              <Outlet />
you should apply style using sx prop

2024-07-24 08:14 UTC, tenadopt commented on package.json
> +    "@types/react-router-dom": "^5.3.3",
Done

2024-07-24 08:15 UTC, tenadopt commented on src/app/routes.tsx
> +const RequireAuth: React.FC<RequireAuthProps> = ({ children }) => {
Done

2024-07-24 08:22 UTC, tenadopt commented on src/features/imageGallery/api/imageService.ts
> +    })) as Image[];
If i write that i have an ERROR 
Argument type (doc: any) => {[p: string]: any, createdAt: Date, id: string} is not assignable to parameter type (value: QueryDocumentSnapshot<DocumentData, DocumentData>, index: number, array: QueryDocumentSnapshot<DocumentData, DocumentData>[]) => Image

2024-07-24 08:26 UTC, tenadopt commented on src/features/works/api/worksServices.ts
> +    }
Done

2024-07-24 08:43 UTC, tenadopt commented on src/features/works/api/worksServices.ts
> +};
If we don't use async we have warning
Promise returned from addDoc is ignored

2024-07-24 08:47 UTC, tenadopt commented on src/features/works/api/worksServices.ts
> +};
Promise returned from setDoc is ignored

2024-07-24 09:02 UTC, tenadopt commented on src/features/works/api/worksServices.ts
> +    return querySnapshot.docs.map((doc) => ({
Done

2024-07-24 09:02 UTC, tenadopt commented on src/app/routes.tsx
> +    );
Done

2024-07-24 09:07 UTC, tenadopt commented on src/pages/Home/ui/HomePage.tsx
> +        loadWorks().catch(console.error);
Done

2024-07-24 09:24 UTC, tenadopt commented on src/pages/Home/ui/HomePage.tsx
> +                                        Delete
Done

2024-07-24 10:29 UTC, tenadopt commented on src/pages/ImageEditor/ui/ImageEditorPage.tsx
> +                            {loading ? 'Saving...' : isEditing ? 'Update Work' : 'Create Work'}
Done

2024-07-25 11:58 UTC, tenadopt commented on src/pages/ImageEditor/ui/ImageEditorPage.tsx
> +                            helperText={errors.description?.message}
Done

2024-07-25 12:02 UTC, tenadopt commented on src/pages/Work/ui/WorkPage.tsx
> +            console.error('Error updating work:', error);
Done

2024-07-25 12:02 UTC, tenadopt commented on src/pages/Work/ui/WorkPage.tsx
> +            ) : null}
Done

2024-07-25 12:04 UTC, tenadopt commented on src/features/imageGallery/api/imageService.ts
> +    })) as Image[];
Done

2024-07-25 12:04 UTC, tenadopt commented on src/pages/ImageFeed/ui/ImageFeedPage.tsx
> +                            </Card>
Done

2024-07-26 07:11 UTC, shev7 requested changes

2024-07-26 07:11 UTC, shev7 commented on src/app/routes.tsx
> +    return (
```suggestion
    const auth = useAppSelector((state) => state.auth);
    
    if (auth.userId) return <Navigate to="/feed" replace />;
    
    return (
```
folow code style

2024-07-26 07:11 UTC, shev7 commented on src/app/routes.tsx
error boundary should be attached to each element, to each route

2024-07-26 07:11 UTC, shev7 commented on src/features/works/api/worksServices.ts
> +    if (!docSnap.exists()) {
```suggestion
    const docSnap = await getDoc(docRef);
    
    if (!docSnap.exists()) {
```

2024-07-26 07:11 UTC, shev7 commented on src/pages/Home/ui/HomePage.tsx
> +        try {
```suggestion
        if (!selectedWorkId) return;
        
        try {
```

2024-07-26 07:11 UTC, shev7 commented on src/pages/ImageEditor/ui/ImageEditorPage.tsx
> +        loadWork().catch(console.error);
```suggestion
        loadWork().catch(console.error);
```
toast

2024-07-26 07:11 UTC, shev7 commented on src/pages/ImageEditor/ui/ImageEditorPage.tsx
> +        try {
```suggestion
        if (!userId) return;
        
        setLoading(true);
        
        try {
```

2024-08-01 13:39 UTC, merged